"""To support Flask/application commands (e.g., ~analogous to manage.py in Django).

Flask comes with command line interface that relies on click framework to natively
support commands tied specific blueprints within application environment. This file
defines those commands. Click is already installed as dependency of Flask.

(Currently used for index management and neighborhood precalculation. It may be nice
to eventually support things like FP generation, DB copying, code coverage, etc.)
"""

import datetime
import itertools
import pathlib
import time

import click
from flask_openapi3 import APIBlueprint
from pymongo import IndexModel, UpdateMany

from genraweb.defs import FILTER
from genraweb.lib.db_connection import open_mongo_db
from genraweb.lib.fp.fputils import FP_INFO, FPGen
from genraweb.lib.fp.precalc import precalc
from genraweb.lib.fp.precalc.utils import calc_max_s0
from genraweb.lib.fp.precalc_hpc.fast_jaccard import make_task_list
from genraweb.lib.properties.genproputils import GenerateProps
from genraweb.resources import DB as DEFAULT_DB

commands_bp = APIBlueprint("commands", __name__)
commands_bp.cli.help = "GenRA DB maintenance commands.  <command> --help for details."

USE_HPC: bool = True  # select newer HPC code over older scikit code


@commands_bp.cli.group()
def index():
    """Index management commands."""
    pass


def get_indexes(DB, target_col="", prefix=""):
    """Build dict of indexed collections, paired with inner dictionaries.

    Each inner dictionary will have following keys:
        - "target_fields": list of fields we're paying attention to in this collection
        - "done": list of target_fields already indexed
        - "not_done": list of target_fields not yet indexed, that we pay attention to

    NOTE: this doesn't report on fields indexed that we don't pay attention to.
    (E.g., "_id", which is auto-generated by mongo.)

    `DB` argument is required, to support `--db` command option.
    NOTE: there may be inconsistency across different deployments, e.g., before feature
    release.

    `target_col` argument is optional.
    """
    targets = {}

    # add fp-specific collections
    fp_ids = set()
    for fp_id, fp_class in FPGen.FPClass.items():
        targets.update({fp_class.fp_output_basename: ["dsstox_cid", "dsstox_sid"]})
        fp_ids.add(fp_id)

    # add other collections
    targets.update(
        {
            # for precalc/network explorer
            # (historically next two lines had ' + list(fp_ids)' at the end but
            # indexing those fields doesn't impact test runtime and increases
            # index size by 65 Gb because mongo indexes duplicate nested fields)
            "fp_info": ["dsstox_cid", "dsstox_sid"],
            FP_INFO: ["dsstox_cid", "dsstox_sid"],
            # for toxcast_fp (+ vendors) generation, see README
            "invitrodb_assay_rslt": ["dsstox_sid"],
            # for analogue image rendering
            "svg": ["dsstox_cid", "dsstox_sid"],
            # dsstox
            "compounds": ["dsstox_cid", "dsstox_sid", "name", "smiles"],
        }
    )

    # add prefix being used for cutover etc.
    targets = {(prefix + key): value for key, value in targets.items()}

    # figure out which ones need to be added
    indexes = {}
    for col, fields in targets.items():
        done = set(
            [index["key"][0][0] for index in DB[col].index_information().values()]
        )
        # to remove miscellaneous like "_id"
        done &= set(fields)
        not_done = set(fields) - done
        indexes[col] = dict(
            target_fields=list(fields),
            done=list(done),
            not_done=list(not_done),
        )

    if target_col:
        # Just the target. Might be worth adding something that allows selecting
        # custom collections(e.g., "test_new_fp")
        assert (
            target_col in indexes
        ), f"{target_col} isn't in list of target collections"
        indexes = {target_col: indexes[target_col]}

    return indexes


def select_db(db):
    """Helper that uses click functionality to return the Pymongo DB instance.
    Used mainly to switch between dev-DB/stg-DB/prod-DB without having to
    adjust `.env`.

    `db` argument corresponds to the `which` argument that gets passed on to
    open_mongo_db(...).

    When this option is invoked and the wrong argument is typed, open_mongo_db(...)
    will return the default DB, so we confirm with the user that we're connected
    to the correct host.
    """
    if db == "":
        # case: default, not specified
        return DEFAULT_DB
    DB = open_mongo_db(which=db)
    host = DB.client.address[0]
    if click.confirm(f"Confirm to use {host}?", abort=True):
        return DB


@index.command("show")
@click.option("--db", default="", type=str, help="`which` arg in open_mongo_db()")
@click.option("--target-col", default="", type=str, help="collection to specify/target")
def show_indexes(db, target_col):
    """For each collection we pay attention to - defined in get_indexes() - click.echo's
    the fields that are indexed and fields that are not.

    `--db` option can be specified, see select_db(...) above.
    `--target-col` option can be specified to target a specific collection.
    """
    DB = select_db(db)
    indexes = get_indexes(DB, target_col)

    prints = []
    for col, col_indexes in indexes.items():
        done, not_done = col_indexes["done"], col_indexes["not_done"]
        prints.append("\n\n>> {col}".format(col=col))
        if done:
            prints.append("> fields indexed: \n{done}".format(done="\n".join(done)))
        if not_done:
            prints.append(
                "> fields MISSING index: \n{not_done}".format(
                    not_done="\n".join(not_done)
                )
            )

    # we use click.echo instead of logger/print because command is run from
    # inside container/click encourages echo over print
    for elem in prints:
        click.echo(elem)


@index.command("create")
@click.option("--db", default="", type=str, help="`which` arg in open_mongo_db()")
@click.option(
    "--prefix", default="", type=str, help="prefix_ prepended to collection names"
)
@click.option("--target-col", default="", type=str, help="collection to specify/target")
def create_indexes(db, prefix, target_col):
    """Creates the indexes. See get_indexes to see and modify which collections and
    fields we pay attention to.

    `--db` option can be specified, see select_db(...) above.
    `--target-col` option can be specified to target a specific collection.
    """
    DB = select_db(db)
    indexes = get_indexes(DB, target_col, prefix)

    todos = {
        col: col_indexes["not_done"]
        for col, col_indexes in indexes.items()
        if col_indexes["not_done"]
    }

    # create the indexes
    counter = 0
    for col, todo in todos.items():
        click.echo(
            f"\nStarting {col}, which has {DB[col].count_documents({})} documents."
        )
        now = time.time()
        DB[col].create_indexes([IndexModel(field) for field in todo])
        runtime = str(datetime.timedelta(seconds=round(time.time() - now)))
        counter += 1
        click.echo(f"...completed in {runtime}. {counter}/{len(todos)} done.")


@index.command("delete")
@click.option("--db", default="", type=str, help="`which` arg in open_mongo_db()")
def delete_indexes(db):
    """Deletes the indexes. See get_indexes to see and modify which collections and
    fields we pay attention to.

    `--db` option can be specified, see select_db(...) above.
    """
    DB = select_db(db)
    indexes = get_indexes(DB)

    cols_keys = {idx: col for idx, col in enumerate(indexes.keys(), 1)}

    cols_keys[0] = "ALL COLLECTIONS"
    cols_keys[-1] = "EXIT"

    click.echo("\nSelect a collection with its option number to delete its indexes:\n")
    for key, col in cols_keys.items():
        click.echo(f"{key:<15} {col}\n")

    while True:
        choice = click.prompt(
            "Enter option number > ",
            type=click.Choice([str(i) for i in cols_keys]),
        )
        choice = int(choice)
        if choice == -1:
            break
        elif choice == 0:
            if click.confirm(
                "Are you sure want to delete all indexes of all these collections?"
            ):
                to_remove = list(cols_keys.values())
            else:
                continue
        elif choice in cols_keys:
            to_remove = [cols_keys[choice]]
        else:
            click.echo("Invalid selection")
            break

        for col in to_remove:
            # note that this drops ALL indexes of the collection - including any
            # non-tracked ones
            DB[col].drop_indexes()
        click.echo(f"deleted indexes for {to_remove}")


@commands_bp.cli.command("precalculate")
@click.option("--db", default="", type=str, help="`which` arg in open_mongo_db()")
def precalculate(db):
    """Flask command to precalculate fp_info collection using scikit-learn. It will
    attempt to use data if it exists, so if the desire is to precalc from scratch, make
    sure to have the /models directly be empty. See the precalc module for more
    information on this entire process.

    Notes
    -----
    - On th029, 32 core machine, this will take 6-10 hours for all FPs. It is CPU
    intensive because the chemical FPs have large number of chems, and this distributes
    the work of neighborhood searching via scikit's multiprocessing capabilities
    - For non-chemical fingerprints, e.g. bio_txct, this will only take ~1 minute

    `--db` option can be specified, see select_db(...) above.

    """
    DB = select_db(db)

    # check volume
    if not click.confirm(
        "\nFOR NON-CHM FP ONLY:"
        "\nDid you set up volume mapping with /models directory?"
        "\n(if not, add something like this to local docker-compose volume: "
        "'${PWD}/models:/genra/models'"
        "\nit may require creating an empty directory '/models at the root "
        "directory of project)\n"
    ):
        click.echo("Please set up volume mapping first.")
        return

    # check user permission setting
    if not click.confirm(
        "\nFOR NON-CHM FP ONLY:"
        "\nAre you accessing this flask environment as the user with same "
        "permissions for WRITE-ing to the /models directory?"
        "\nThis can be done with one of the following:"
        "\n- using '-u `id -u`' option when docker-exec'ing to access the flask"
        "environment\n- having something like "
        "'user: ${UID}:500' in the docker-compose setting\n"
    ):
        click.echo("Please access as the right user")
        return

    # check right fp_info collection
    if not click.confirm(f"\nConfirm update to {FP_INFO}\n"):
        click.echo("Please configure desired value for $GNERA_FP_INFO_COLLECTION")
        return

    # easier to fail now than after waiting a long time pulling some large data
    if not USE_HPC:
        try:
            pathlib.Path("models/empty_test_directory").mkdir(
                parents=True, exist_ok=True
            )
            pathlib.Path("models/empty_test_directory").rmdir()
        except PermissionError:
            click.echo("Please access as the right user")
            return

    fp_ids = list(FPGen.FPClass.keys())
    fp_keys = {idx: fp_id for idx, fp_id in enumerate(fp_ids, 1)}
    fp_keys[0] = "ALL FINGERPRINTS"
    fp_keys[-1] = "EXIT"
    fp_keys[98] = "ALL CHEMICAL FINGERPRINTS"
    fp_keys[99] = "ALL NON-CHEMICAL FINGERPRINTS"
    click.echo("\nSelect a fingerprint to precalculate for:\n")
    for key, fp_id in fp_keys.items():
        click.echo(f"{key:<15} {fp_id}\n")
    choice = click.prompt(
        "Enter option number > ",
        type=click.Choice([str(i) for i in fp_keys]),
    )
    choice = int(choice)
    if choice == -1:
        return
    elif choice == 0:
        # `fp_ids` already has all
        pass
    elif choice == 98:
        fp_ids = [fp_id for fp_id in fp_ids if fp_id.startswith("chm_")]
    elif choice == 99:
        fp_ids = [fp_id for fp_id in fp_ids if not fp_id.startswith("chm_")]
    elif choice in fp_keys:
        fp_ids = [fp_keys[choice]]
    else:
        click.echo("Invalid selection")
        return

    filters = [i for i in FILTER if not FILTER[i].get("skip")]
    filter_keys = {idx: sel_by for idx, sel_by in enumerate(filters, 1)}
    filter_keys[0] = "ALL FILTERS"
    filter_keys[-1] = "EXIT"
    filter_keys[99] = "ALL RESTRICTING FILTERS (no no_filter)"
    click.echo("\nSelect a filter to apply:\n")
    for key, sel_by in filter_keys.items():
        click.echo(f"{key:<15} {sel_by}\n")
    choice = click.prompt(
        "Enter option number > ",
        type=click.Choice([str(i) for i in filter_keys]),
    )
    choice = int(choice)
    if choice == -1:
        return
    elif choice == 0:
        # `filters` already has all
        pass
    elif choice == 99:
        filters = [sel_by for sel_by in filters if sel_by != "no_filter"]
    elif choice in filter_keys:
        filters = [filter_keys[choice]]
    else:
        click.echo("Invalid selection")
        return

    # see if from scratch
    if click.confirm(
        "\nStart from scratch?"
        "\nWARNING: starting from scratch will first remove precalculated fields "
        "for these fingperints and filters."
    ):
        if (
            any(["chm" in fp_id for fp_id in fp_ids])
            and "no_filter" in filters
            and not click.confirm(
                "\nChemical fingerprint(s) with no_filter has been selected, "
                "are you doubly sure?"
            )
        ):
            return

        fields = [
            (fp_id, f"{fp_id}.{sel_by}")
            for fp_id, sel_by in itertools.product(fp_ids, filters)
        ]

        DB[FP_INFO].bulk_write(
            [
                UpdateMany(
                    {fp_id: {"$ne": None}},
                    {"$unset": {key: 1 for fp_id, key in fields}},
                )
            ]
        )

    chm_fps = [i for i in fp_ids if i.startswith("chm_")]
    non_chm_fps = [i for i in fp_ids if not i.startswith("chm_")]
    mode = click.prompt(
        "Enter mode name > ",
        type=click.Choice(["jaccard", "cosine", "euclid"]),
    )
    for fp_id, filter_by in itertools.product(chm_fps, filters):
        click.echo(f"Setting up job list collection fj_{fp_id}_{filter_by}")
        try:
            make_task_list(
                {
                    "FJ_FP_ID": fp_id,
                    "FJ_SEL_BY": filter_by,
                    "FJ_BATCH_SIZE": 1000,
                    "FJ_COLLECTION": f"fj_{fp_id}_{filter_by}",
                    "FJ_SIM_MODE": mode,
                }
            )
        except ValueError:
            print("Rejected, probably already exists")

    precalc.precalculate(non_chm_fps, filters)


@commands_bp.cli.command("genprops")
@click.option("--db", default="", type=str, help="`which` arg in open_mongo_db()")
def genprops(db):
    """Flask command to generate some (physchem) properties that are not included
    in upstream DBs.

    `--db` option can be specified, see select_db(...) above.
    """
    DB = select_db(db)
    choices = {
        "0": "MISSING: Eligible chemicals (~ has SMILE) with missing props data",
        "1": "ALL: All eligible chemicals (overwrite)",
    }
    for key, description in choices.items():
        click.echo(f"{key:<15} {description}\n")
    choice_key = click.prompt(
        "Enter option number > ",
        type=click.Choice([str(i) for i in choices]),
    )
    choice = choices[choice_key].split(":")[0]
    batcher = GenerateProps(DB, choice)
    batcher.queue_batches()


@commands_bp.cli.command("max_sim")
@click.option("--db", default="", type=str, help="`which` arg in open_mongo_db()")
def max_sim(db):
    """Flask command to generate max_sim field for all chemicals in fp_info."""
    DB = select_db(db)
    calc_max_s0(DB)


if __name__ == "__main__":
    commands_bp.cli()
