"""Generate mongo export scripts for standalone DB.

This script generates a bash script that can be used to dump a mongo database to a set
of gzipped json files.  The script is written to _dump_db.sh.  _index_db.sh (also
written) can be used to generate indexes for the restored DB.
"""

import json
import time
from itertools import chain
from pathlib import Path
from pprint import pprint

import inquirer

from genraweb.commands import get_indexes
from genraweb.lib.db_connection import open_mongo_db

# Data / queries for a BPA only mini-dump
BPA_NN = [
    "DTXCID30182",
    "DTXCID001771",
    "DTXCID602360",
    "DTXCID70716",
    "DTXCID10465",
    "DTXCID406081",
    "DTXCID402529",
    "DTXCID60220",
    "DTXCID606",
    "DTXCID501124",
    "DTXCID3024495",
    "DTXCID0031269",
    "DTXCID002528",
    "DTXCID2014576",
    "DTXCID902312",
]
queryBPA = {"$or": [{"dsstox_cid": "DTXCID30182"}, {"dtxcid": "DTXCID30182"}]}
queryBPANN = {"$or": [{"dsstox_cid": {"$in": BPA_NN}}, {"dtxcid": {"$in": BPA_NN}}]}
queryALL = {}

# Set queries to queryALL for full dump
queryBPA = queryALL
queryBPANN = queryALL

STANDARD = {
    "compounds": queryBPANN,
    "invitrodb_assay_rslt": queryALL,
    "physprop": queryBPANN,
    "toxcast_assays": queryALL,
    "toxref_effects": queryALL,
    "toxref_guideline": queryALL,
    "fp_info": queryBPANN,
    # "standard" FPs
    "chemotypes_fp": queryBPANN,
    "chms_fp": queryBPANN,
    "aim_fp": queryBPANN,
    "toxcast_fp": queryBPANN,
    "toxcast_atg_fp": queryBPANN,
    "toxcast_bsk_fp": queryBPANN,
    "toxcast_nvs_fp": queryBPANN,
    "toxref_tr_fp": queryBPANN,
    "toxrefdb_v2": queryALL,
}

done = False
defaults = []
old_db = None
while not done:
    # Ask which environment to dump
    questions = [
        inquirer.List(
            "db",
            message="Dump which DB (arrow keys, enter)?",
            choices=["DEV", "STG", "PROD"],
        )
    ]
    answers = inquirer.prompt(questions)
    db = answers["db"]
    src = open_mongo_db(which=db)
    src_col = list(src.list_collection_names())
    missing = set(STANDARD) - set(src_col)
    if missing:
        print(f"Missing standard collections: {missing}")
        exit(1)

    if db != old_db:
        defaults = []
    old_db = db
    print(db)
    print(src._uri)

    full_src_col = list(src_col)  # copy for exclusion below
    print("Including the following standard collections:")
    pprint(STANDARD)
    excludes = (
        ("collections tagged 'DELME'", lambda x: "DELME" not in x),
        ("collections tagged 'BKUP'", lambda x: "BKUP" not in x),
        ("collections ending in '_test'", lambda x: not x.endswith("_test")),
    )
    for desc, filt in excludes:
        full_n = len(src_col)
        src_col = [i for i in src_col if filt(i)]
        filt_n = full_n - len(src_col)
        if filt_n:
            print(f"Ignoring {filt_n} {desc}.")
    print(
        "Select additional collections from the following list.\n"
        "Add collections only *if* they are appropriate for release.\n"
        "Use arrow keys and space to toggle selections"
    )
    others = sorted(set(src_col) - set(STANDARD))

    questions = [
        inquirer.Checkbox(
            "extras", message="Add collections", choices=others, default=defaults
        ),
    ]
    extras = inquirer.prompt(questions)["extras"]
    defaults = extras
    print(f"Dumping DB {db}")
    print("Standard collections")
    pprint(STANDARD)
    print("Extra collections")
    pprint(extras)

    questions = [
        inquirer.Confirm("done", message="Continue (no = revise)"),
    ]
    done = inquirer.prompt(questions)["done"]

# Now build _dump_db.sh
todo = set(STANDARD) | set(extras)
cmd = []
limit = None
for collection in todo:
    cmd.append(f"echo Dumping {collection}")
    filename = f"genra_{db}_{collection}.*.gz"
    sub = [
        f"[ -e {filename} ] && echo {filename} exists, skipping ||",
        "docker run --rm -it",
        "    mongo:6 mongoexport",
        "    --quiet",
        f"    --collection={collection}",
        f'    --uri="{src._uri}"',
    ]
    if limit:
        sub.append(f"    --limit={limit}")
    query = STANDARD.get(collection, {})
    if query:
        query = json.dumps(query).replace('"', '\\"').replace("$", "\\$")
        sub.append(f'    --query="{query}"')
    filename = f"genra_{db}_{collection}.$TS.gz"
    sub.append(f"    | gzip > {filename}")
    cmd.append(" \\\n".join(sub) + "\n")

cmd[:0] = [
    f"# Generated by dump_db.py {time.asctime()} UTC\n",
    "TS=$(date +%Y%m%d_%H%M%S)",
]
cmd = "\n".join(cmd)
Path("_dump_db.sh").write_text(cmd)
print("Dump script written to _dump_db.sh")

# Write _index_db.sh
cmd = []
indexes = get_indexes(src)
for collection in indexes:
    for field in chain(indexes[collection]["done"], indexes[collection]["not_done"]):
        cmd.append(f"db.{collection}.createIndex({{{field}: 1}})")
cmd = "\n".join(cmd)
Path("_index_db.sh").write_text(cmd)
print("Index script written to _index_db.mongosh")
