"""This module takes in a CollectionLevelCheck object and processes its
information into JSON objects that are more human readable and writes
them to file.

Two files ('reports') are written:
- shallow_report : some summary information that can be navigated by
simply opening and eyeballing the file
- deep_report : detailed information and may be useful when navigating it
programatically"""

import json
import os

from chemical_level import NoFPKeyException


class ReportGenerator:
    """
    A class that writes the comparison information into human readable
    JSON files. Each `prepare_<section_name>_section()` corresponds to each
    information section from CollectionLevelCheck object, and writes a report
    for it (for each of shallow and deep).

    Report(s) are generated by calling the `run()` method.
    """

    def __init__(self, collection_level_check, report_label):
        """
        Parameters
        ----------
                collection_level_check : CollectionLevelCheck object
                        This class uses the `info` field of this parameter object
        """
        self.info = collection_level_check.info
        self.fp_name = collection_level_check.fp_name
        self.identifier_class = collection_level_check.identifier_class
        self.shallow_report = {}
        self.deep_report = {}
        self.report_label = report_label

    def update_reports(self, section_key, shallow_section_report, deep_section_report):
        report_name = f"{section_key}_report"
        self.shallow_report.update({report_name: shallow_section_report})
        self.deep_report.update({report_name: deep_section_report})

    def prepare_meta_section(self):
        section_key = "meta"
        shallow_section_report = {}
        deep_section_report = {}

        id_name = self.identifier_class.id_name

        for key, val in self.info[f"{section_key}_info"].items():
            if not key.startswith(id_name):
                shallow_section_report.update({key: val})
            deep_section_report.update({key: val})

        self.update_reports(section_key, shallow_section_report, deep_section_report)

    def prepare_fields_error_section(self):
        section_key = "fields_error"
        shallow_section_report = {}
        deep_section_report = {}

        for key, val in self.info[f"{section_key}_info"].items():
            shallow_val = {k: v for k, v in val.items() if "list" not in k}
            shallow_section_report.update({key: shallow_val})
            deep_section_report.update({key: val})

        self.update_reports(section_key, shallow_section_report, deep_section_report)

    def prepare_chemicals_comparison_section(self):
        section_key = "chemicals_comparison_subset"
        shallow_section_report = {}
        deep_section_report = {}

        id_name = self.identifier_class.id_name

        no_fp_key = {}
        fp_stats = {}
        for identifier, info in self.info[f"{section_key}_info"].items():
            fp_changes = {}
            for fp, fp_info in info.items():

                if isinstance(fp_info, NoFPKeyException):
                    no_fp = no_fp_key.get(identifier, None)
                    if no_fp is None:
                        no_fp_key.update({identifier: [fp]})
                    else:
                        no_fp_key[identifier] += [fp]
                    continue

                added, removed = fp_info["added"], fp_info["removed"]
                if len(added) == 0 and len(removed) == 0:
                    continue

                # overall stats
                if fp not in fp_stats:
                    fp_stats.update(
                        {
                            fp: {
                                "num_added": 0,
                                "num_added_desc": (
                                    "number of chemicals that had increase"
                                    " in this FP array"
                                ),
                                "num_removed": 0,
                                "num_removed_desc": (
                                    "number of chemicals that had decrease"
                                    " in this FP array"
                                ),
                            }
                        }
                    )
                for action_list, action_type in (
                    (added, "added"),
                    (removed, "removed"),
                ):
                    if len(action_list) > 0:
                        fp_stats[fp][f"num_{action_type}"] += 1

                        # deep report specific
                        fp_changes.update(
                            {
                                f"{action_type}_in_{fp}": action_list,
                                f"{action_type}_in_{fp}_desc": (
                                    f"{id_name}s of chemical with elements in"
                                    f" FP array {action_type}"
                                ),
                            }
                        )
            if fp_changes:
                deep_section_report.update({identifier: fp_changes})

        shallow_section_report.update(fp_stats)
        deep_section_report.update(fp_stats)

        shallow_section_report.update(
            {f"num_{id_name}s_with_FPKeyException": len(no_fp_key)}
        )
        deep_section_report.update(
            {f"num_{id_name}s_with_FPKeyException": len(no_fp_key)}
        )

        deep_section_report.update({"chemicals_with_FPKeyException": no_fp_key})

        self.update_reports(section_key, shallow_section_report, deep_section_report)

    def write_json(self, fname, data):
        """Since the entire script for comparison is likely to be run from the
        root genra directory, need to add the directory of it/this module
        to the path of the JSON file being saved.

        Saves json report in directory called `reports/<self.report_label>` (created if
        DNE) in the same directory as this module.
        """
        module_dir = os.path.realpath(
            os.path.join(os.getcwd(), os.path.dirname(__file__))
        )

        report_dir_path = os.path.join(module_dir, f"reports/{self.report_label}/")
        if not os.path.exists(report_dir_path):
            os.makedirs(report_dir_path)

        report_path = os.path.join(report_dir_path, fname)
        with open(report_path, "w+") as file:
            json.dump(data, file, indent=4)

    def run(self):
        # FIXME: once deep report portion working, uncomment relevant parts below

        self.prepare_meta_section()
        self.prepare_fields_error_section()
        self.prepare_chemicals_comparison_section()
        self.write_json(f"shallow_report_{self.fp_name}.json", self.shallow_report)
        # self.write_json(f"deep_report_{self.fp_name}.json", self.deep_report)
